# Generated by Django 4.2.8 on 2024-01-05 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polytheism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
