# Generated by Django 4.2.8 on 2024-01-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0003_magic_tarot'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='magic',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='magic',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='polytheism',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='polytheism',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='polytheism',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='tarot',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tarot',
            name='time_create',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='tarot',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
