# Generated by Django 4.2.8 on 2024-01-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0004_magic_is_published_magic_time_create_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magic',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterModelOptions(
            name='polytheism',
            options={'ordering': ['-time_create']},
        ),
        migrations.AlterModelOptions(
            name='tarot',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Image'),
        ),
        migrations.AddIndex(
            model_name='magic',
            index=models.Index(fields=['-time_create'], name='tarotmagic__time_cr_64d610_idx'),
        ),
        migrations.AddIndex(
            model_name='polytheism',
            index=models.Index(fields=['-time_create'], name='tarotmagic__time_cr_88dc7b_idx'),
        ),
        migrations.AddIndex(
            model_name='tarot',
            index=models.Index(fields=['-time_create'], name='tarotmagic__time_cr_743f38_idx'),
        ),
    ]
