# Generated by Django 4.2.8 on 2024-01-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0006_magic_image_polytheism_image_tarot_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='magic',
            name='glob_slug',
            field=models.CharField(default='Magic', max_length=255),
        ),
        migrations.AddField(
            model_name='polytheism',
            name='glob_slug',
            field=models.CharField(default='Polytheism', max_length=255),
        ),
        migrations.AddField(
            model_name='tarot',
            name='glob_slug',
            field=models.CharField(default='Tarot', max_length=255),
        ),
    ]
