# Generated by Django 4.2.8 on 2024-01-09 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0007_magic_glob_slug_polytheism_glob_slug_tarot_glob_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='photos', verbose_name='Image')),
            ],
        ),
        migrations.AlterField(
            model_name='magic',
            name='glob_slug',
            field=models.CharField(default='MAGIC', max_length=255),
        ),
        migrations.AlterField(
            model_name='polytheism',
            name='glob_slug',
            field=models.CharField(default='POLYTHEISM', max_length=255),
        ),
        migrations.AlterField(
            model_name='tarot',
            name='glob_slug',
            field=models.CharField(default='TAROT', max_length=255),
        ),
    ]
