# Generated by Django 4.2.8 on 2024-01-09 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0008_offer_alter_magic_glob_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='magic',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
        migrations.AlterField(
            model_name='polytheism',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
        migrations.AlterField(
            model_name='tarot',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=1),
        ),
    ]
