# Generated by Django 4.2.8 on 2024-01-23 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0009_alter_magic_is_published_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='magic',
            options={'ordering': ['-time_create'], 'verbose_name': 'Магия', 'verbose_name_plural': 'Магия'},
        ),
        migrations.AlterModelOptions(
            name='mainpage',
            options={'verbose_name': 'Главная', 'verbose_name_plural': 'Главная'},
        ),
        migrations.AlterModelOptions(
            name='offer',
            options={'verbose_name': 'Услуги', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.AlterModelOptions(
            name='polytheism',
            options={'ordering': ['-time_create'], 'verbose_name': 'Политеизм', 'verbose_name_plural': 'Политеизм'},
        ),
        migrations.AlterModelOptions(
            name='tarot',
            options={'ordering': ['-time_create'], 'verbose_name': 'Таро', 'verbose_name_plural': 'Таро'},
        ),
        migrations.AddField(
            model_name='magic',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tarotmagic.offer'),
        ),
        migrations.AddField(
            model_name='polytheism',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tarotmagic.offer'),
        ),
        migrations.AddField(
            model_name='tarot',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tarotmagic.offer'),
        ),
    ]
