# Generated by Django 4.2.8 on 2024-01-24 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarotmagic', '0010_alter_magic_options_alter_mainpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='polytheism',
            options={'ordering': ['-time_create'], 'verbose_name': 'Неоязычество', 'verbose_name_plural': 'Неоязычество'},
        ),
        migrations.RemoveField(
            model_name='magic',
            name='glob_slug',
        ),
        migrations.RemoveField(
            model_name='polytheism',
            name='glob_slug',
        ),
        migrations.RemoveField(
            model_name='tarot',
            name='glob_slug',
        ),
        migrations.AddField(
            model_name='magic',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='polytheism',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='tarot',
            name='slug',
            field=models.CharField(default='', max_length=255),
        ),
    ]
